### ISSUE TITLE
Missing /static/admin/css/base.css

### ISSUE THREAD

**Issue by Sepiidae** [ubccr/coldfront#191]
Looks like the css files for the admin interface are missing. So far I have confirmed the following are not present in the repository. 

/static/admin/cass/base.css
/admin/css/dashboard.css
/admin/css/responsive.css

**Comment by mkzia** [comment]
Hello,
Do you have debug=False or True?

**Comment by zooley** [comment]
Just chiming in to say that if you're looking for the files' source code, you won't find them in the ColdFront repository as they come from Django:

https://github.com/django/django/tree/master/django/contrib/admin/static/admin/css

I think @mkzia's question is in reference to how Django handles static file loading when debugging is off vs on. Possible help: https://stackoverflow.com/a/52488425

Admittedly, it's been a while since I've used Django so need to refresh my own memory on a lot of this.
